/**
 * Renders every generated token sheet from `./index.ts`. Run from the
 * repository root with `bun run tokens:generate`; the apps' drift tests
 * compare the committed files against these renderers, so a hand edit to a
 * generated file fails the gate until the model changes instead.
 */
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  font,
  gradient,
  labColor,
  legacyWeb,
  radius,
  semantic,
  typeScale,
  websiteApp,
} from "./index";

const HEADER = "/* Generated by packages/design-tokens/src/generate.ts from src/index.ts. Do not edit; run `bun run tokens:generate`. */";

const lower = (hex: string) => hex.toLowerCase();
const rgba = (hex: string, alpha: number) => {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${alpha.toFixed(2)})`;
};

/** `apps/mlai/src/tokens.generated.css`: Tailwind theme + shadcn :root. */
export function renderWebTokensCss(): string {
  const theme = [
    `  --font-sans: ${font.sans};`,
    `  --font-display: ${font.display};`,
    `  --font-mono: ${font.mono};`,
    "",
    "  /* Legacy utility colours (bg-bg, text-text-dim, hover:bg-primary-hover). */",
    ...Object.entries(legacyWeb).map(([k, v]) => `  --color-${k}: ${lower(v)};`),
    "",
    "  /* Typography modular scale (Major Third 1.250) */",
    ...Object.entries(typeScale).map(([k, v]) => `  --text-${k}: ${v};`),
  ];
  const root = [
    "  /* Lab raw values + signature gradient (used directly by .grad-text, persona dots) */",
    ...Object.entries(labColor).map(([k, v]) => `  --${k}: ${lower(v)};`),
    `  --accent-soft: ${rgba(labColor.cyan, 0.14)};`,
    `  --accent-line: ${rgba(labColor.cyan, 0.3)};`,
    `  --grad: linear-gradient(92deg, ${gradient.map(lower).join(", ")});`,
    "",
    "  /* shadcn semantic tokens. primary-foreground and destructive-foreground",
    "     are dark ink because primary (cyan) and destructive (light red) are",
    "     light: >= 4.5:1 (WCAG AA) text contrast on both. */",
    ...Object.entries(semantic).map(([k, v]) => `  --${k}: ${v};`),
    `  --radius: ${radius.base};`,
  ];
  const inline = [
    "  --font-heading: var(--font-display);",
    ...Object.keys(semantic).map((k) => `  --color-${k}: var(--${k});`),
    ...Object.entries(radius.scale).map(([k, m]) =>
      m === 1 ? `  --radius-${k}: var(--radius);` : `  --radius-${k}: calc(var(--radius) * ${m});`,
    ),
  ];
  return [
    HEADER,
    "@theme {",
    ...theme,
    "}",
    "",
    ":root {",
    ...root,
    "}",
    "",
    "@theme inline {",
    ...inline,
    "}",
    "",
  ].join("\n");
}

/** `apps/website-app/packages/ui/src/styles/tokens.css`: that app's layout vocabulary. */
export function renderWebsiteAppTokensCss(): string {
  const w = websiteApp;
  const lines = [
    HEADER,
    ":root {",
    "  color-scheme: dark;",
    "  /* Lab identity. Canonical names first, then this app's aliases. */",
    ...Object.entries(labColor).map(([k, v]) => `  --${k}: ${lower(v)};`),
    "  --bg: var(--ink);",
    `  --panel: ${w.color.panel};`,
    `  --panel-raised: ${w.color.panelRaised};`,
    `  --line: ${w.color.line};`,
    `  --text: ${w.color.text};`,
    `  --muted: ${w.color.muted};`,
    "  --purple: var(--violet);",
    "  --green: var(--emerald);",
    "  --warn: var(--amber);",
    "  /* Text ramp: --text for headings, --text-body for prose, --muted for",
    "     supporting copy, --text-faint for footer labels. */",
    `  --text-body: ${w.color.textBody};`,
    `  --text-faint: ${w.color.textFaint};`,
    "",
    `  --font-body: ${w.font.body};`,
    `  --font-heading: ${w.font.heading};`,
    `  --font-mono: ${w.font.mono};`,
    "",
    "  /* Radius scale (px). --radius below is shadcn's and stays; its primitives read it. */",
    ...Object.entries(w.radiusPx).map(([k, v]) => `  --radius-${k}: ${v};`),
    "",
    "  /* Type scale, ~1.25 from the 14px body; display steps set by the hero clamps. */",
    ...Object.entries(w.size).map(([k, v]) => `  --size-${k}: ${v};`),
    `  --tracking-display: ${w.trackingDisplay};`,
    `  --leading-display: ${w.leadingDisplay};`,
    "",
    "  /* Spacing steps the layout sheet consumes by name. */",
    ...Object.entries(w.space).map(([k, v]) => `  --space-${k}: ${v};`),
    "  /* Product accents. AGENTS.md fixes these three: WDBX cyan, ABI violet, Abbey emerald. */",
    "  --accent-wdbx: var(--cyan);",
    "  --accent-abi: var(--violet);",
    "  --accent-abbey: var(--emerald);",
    "",
    "  /* shadcn/ui CSS variables mapped onto Lab tokens (cyan primary). */",
    "  --background: var(--bg);",
    "  --foreground: var(--text);",
    "  --card: var(--panel);",
    "  --card-foreground: var(--text);",
    "  --popover: var(--panel-raised);",
    "  --popover-foreground: var(--text);",
    "  --primary: var(--cyan);",
    `  --primary-foreground: ${w.color.primaryForeground};`,
    "  --secondary: var(--panel-raised);",
    "  --secondary-foreground: var(--text);",
    "  --muted-foreground: var(--muted);",
    "  --accent: color-mix(in srgb, var(--cyan) 14%, var(--panel));",
    "  --accent-foreground: var(--text);",
    `  --destructive: ${w.color.destructive};`,
    "  --border: var(--line);",
    "  --input: var(--line);",
    "  --ring: color-mix(in srgb, var(--cyan) 55%, transparent);",
    `  --radius: ${radius.base};`,
    "}",
    "",
    "@theme inline {",
    "  --color-background: var(--background);",
    "  --color-foreground: var(--foreground);",
    "  --color-card: var(--card);",
    "  --color-card-foreground: var(--card-foreground);",
    "  --color-popover: var(--popover);",
    "  --color-popover-foreground: var(--popover-foreground);",
    "  --color-primary: var(--primary);",
    "  --color-primary-foreground: var(--primary-foreground);",
    "  --color-secondary: var(--secondary);",
    "  --color-secondary-foreground: var(--secondary-foreground);",
    "  --color-muted: var(--panel);",
    "  --color-muted-foreground: var(--muted-foreground);",
    "  --color-accent: var(--accent);",
    "  --color-accent-foreground: var(--accent-foreground);",
    "  --color-destructive: var(--destructive);",
    "  --color-border: var(--border);",
    "  --color-input: var(--input);",
    "  --color-ring: var(--ring);",
    "  --radius-sm: calc(var(--radius) - 4px);",
    "  --radius-md: calc(var(--radius) - 2px);",
    "  --radius-lg: var(--radius);",
    "  --radius-xl: calc(var(--radius) + 4px);",
    "  --font-sans: var(--font-body);",
    "  --font-mono: var(--font-mono);",
    "}",
    "",
  ];
  return lines.join("\n");
}

/** `apps/website-app/packages/ui/src/tokens.ts`: the same data in TypeScript. */
export function renderWebsiteAppTokensTs(): string {
  const w = websiteApp;
  // Prettier's choice: double quotes unless the value contains one, then single.
  const q = (s: string) => (s.includes('"') && !s.includes("'") ? `'${s}'` : JSON.stringify(s));
  return [
    "// Generated by packages/design-tokens/src/generate.ts from src/index.ts.",
    "// Do not edit; run `bun run tokens:generate`.",
    "export const color = {",
    `  bg: ${q(lower(labColor.ink))},`,
    `  panel: ${q(w.color.panel)},`,
    `  panelRaised: ${q(w.color.panelRaised)},`,
    `  line: ${q(w.color.line)},`,
    `  text: ${q(w.color.text)},`,
    `  muted: ${q(w.color.muted)},`,
    `  cyan: ${q(lower(labColor.cyan))},`,
    `  purple: ${q(lower(labColor.violet))},`,
    `  green: ${q(lower(labColor.emerald))},`,
    `  warn: ${q(lower(labColor.amber))},`,
    "} as const;",
    "export const productAccent = {",
    "  wdbx: color.cyan,",
    "  abi: color.purple,",
    "  abbey: color.green,",
    "} as const;",
    "export const font = {",
    `  body: ${q(w.font.body)},`,
    `  heading: ${q(w.font.heading)},`,
    `  mono: ${q(w.font.mono)},`,
    "} as const;",
    "export type ProductAccent = keyof typeof productAccent;",
    "",
  ].join("\n");
}

/** Repository-relative outputs, in the order they are written. */
export const outputs = [
  { path: "apps/mlai/src/tokens.generated.css", render: renderWebTokensCss },
  { path: "apps/website-app/packages/ui/src/styles/tokens.css", render: renderWebsiteAppTokensCss },
  { path: "apps/website-app/packages/ui/src/tokens.ts", render: renderWebsiteAppTokensTs },
] as const;

export function writeAll(repoRoot: string): string[] {
  const written: string[] = [];
  for (const { path: rel, render } of outputs) {
    const target = path.join(repoRoot, rel);
    if (!existsSync(path.dirname(target))) continue;
    writeFileSync(target, render());
    written.push(target);
  }
  return written;
}

if (import.meta.main) {
  const repoRoot = path.resolve(import.meta.dirname, "../../..");
  for (const written of writeAll(repoRoot)) console.log(`wrote ${path.relative(repoRoot, written)}`);
}
