export const PERSONAS = {
  ABBEY: {
    color: "cyan",
    hex: "#00f2ff",
    label: "Ethical_Compliance",
    mission: "PRESERVING_CORE_INTEGRITY",
    protocol: "ABBEY_SECURE_INTEGRITY_SHIELD",
    accentClass: "text-accent",
    accentLightClass: "text-accent-light",
    borderClass: "border-accent/30",
    bgClass: "bg-accent/5",
    glowClass: "from-accent/25 to-transparent",
    orbClass: "bg-accent shadow-[0_0_80px_rgba(0,242,255,0.4)]",
    neuralTheme: "staggered-data-active",
    animationClass: "animate-abbey",
  },
  AVIVA: {
    color: "purple",
    hex: "#d900ff",
    label: "Advanced_Research",
    mission: "NEURAL_SYNTHETIC_EXPANSION",
    protocol: "AVIVA_HYPER_COMPUTE_OVERCLOCK",
    accentClass: "text-accent",
    accentLightClass: "text-accent-light",
    borderClass: "border-accent/40",
    bgClass: "bg-accent/10",
    glowClass: "from-accent/30 to-transparent",
    orbClass: "bg-accent shadow-[0_0_80px_rgba(217,0,255,0.5)]",
    neuralTheme: "quantum-distortion-v4",
    animationClass: "animate-aviva",
  },
  ABI: {
    color: "orange",
    hex: "#ffbb00",
    label: "Regulatory_Oversight",
    mission: "DYNAMIC_MODERATION_SYNC",
    protocol: "ABI_MEDIATION_LAYER_ACTIVE",
    accentClass: "text-accent",
    accentLightClass: "text-accent-light",
    borderClass: "border-accent/30",
    bgClass: "bg-accent/5",
    glowClass: "from-accent/20 to-transparent",
    orbClass: "bg-accent shadow-[0_0_80px_rgba(255,187,0,0.4)]",
    neuralTheme: "regulatory-buffer-sync",
    animationClass: "animate-abi",
  },
} as const;

export type PersonaType = keyof typeof PERSONAS;
