// Generated by packages/design-tokens/src/generate.ts from src/index.ts.
// Do not edit; run `bun run tokens:generate`.
export const color = {
  bg: "#05070d",
  panel: "#0e1218",
  panelRaised: "#171b21",
  line: "rgba(255, 255, 255, 0.1)",
  text: "#e6edf6",
  muted: "#93a4ba",
  cyan: "#22d3ee",
  purple: "#a855f7",
  green: "#34d399",
  warn: "#fbbf24",
} as const;
export const productAccent = {
  wdbx: color.cyan,
  abi: color.purple,
  abbey: color.green,
} as const;
export const font = {
  body: '"Geist Sans", "Geist", system-ui, sans-serif',
  heading: '"Spectral", Georgia, serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;
export type ProductAccent = keyof typeof productAccent;
